services:
  db:
    image: postgres:16
    container_name: abitassistant_postgres
    restart: always
    # Всі данні в environment поміняйте на свої, але щоб співпадало з config.py
    environment:
      POSTGRES_DB: abit_db
      POSTGRES_USER: name
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    container_name: abitassistant_bot
    shm_size: 1gb
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://name:password@db:5432/abit_db # Тут поміняти назви name, password і abit_db
    command: python bot.py

volumes:
  pgdata:
