[project]
name = "competition-check-telegram-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram>=3.19.0",
    "aiosqlite>=0.21.0",
    "selenium>=4.30.0",
    "sqlalchemy>=2.0.40",
]
